# ===== ????????? ??????? =====
server.port=8081

# ===== ????????? KAFKA =====
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=joke-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.jokekafkaconsumer.dto.JokeMessage
#spring.kafka.listener.ack-mode=record
spring.kafka.listener.ack-mode=manual
spring.kafka.listener.concurrency=1
spring.kafka.listener.poll-timeout=3000

# ===== ????????? POSTGRESQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/jokes_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5

# ===== JPA ????????? =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.open-in-view=false

# ???????????? ??????????? Kafka
logging.level.org.apache.kafka=DEBUG
logging.level.org.springframework.kafka.listener=TRACE
logging.level.org.springframework.transaction=DEBUG

# ??????????? SQL

# ??????????? ?????? ???????


# ??????????? SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


# ===== ??????????? =====
logging.level.com.example.jokekafkaconsumer=DEBUG
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka.clients.consumer=INFO
#logging.level.org.hibernate.SQL=INFO

# ===== ???????? =====
management.endpoints.web.exposure.include=health,info,metrics
###################################################################
# ??????????? ?????????? Spring

logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG

# ??????????? Hibernate ? ????????

logging.level.org.hibernate.transaction=DEBUG

# ??????????? ?????? ???????
# ????????? ??? Kafka consumer (?????!)
# Kafka ?????????
